package com.imooc.pojo;

import java.util.Date;

public class ItemsParam {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.item_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.produc_place
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String producPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.foot_period
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String footPeriod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.brand
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String brand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.factory_name
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String factoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.factory_address
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String factoryAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.packaging_method
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String packagingMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.weight
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.storage_method
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String storageMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.eat_method
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String eatMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_param.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.id
     *
     * @return the value of items_param.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.id
     *
     * @param id the value for items_param.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.item_id
     *
     * @return the value of items_param.item_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.item_id
     *
     * @param itemId the value for items_param.item_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.produc_place
     *
     * @return the value of items_param.produc_place
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getProducPlace() {
        return producPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.produc_place
     *
     * @param producPlace the value for items_param.produc_place
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setProducPlace(String producPlace) {
        this.producPlace = producPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.foot_period
     *
     * @return the value of items_param.foot_period
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getFootPeriod() {
        return footPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.foot_period
     *
     * @param footPeriod the value for items_param.foot_period
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setFootPeriod(String footPeriod) {
        this.footPeriod = footPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.brand
     *
     * @return the value of items_param.brand
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getBrand() {
        return brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.brand
     *
     * @param brand the value for items_param.brand
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setBrand(String brand) {
        this.brand = brand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.factory_name
     *
     * @return the value of items_param.factory_name
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getFactoryName() {
        return factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.factory_name
     *
     * @param factoryName the value for items_param.factory_name
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setFactoryName(String factoryName) {
        this.factoryName = factoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.factory_address
     *
     * @return the value of items_param.factory_address
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getFactoryAddress() {
        return factoryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.factory_address
     *
     * @param factoryAddress the value for items_param.factory_address
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setFactoryAddress(String factoryAddress) {
        this.factoryAddress = factoryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.packaging_method
     *
     * @return the value of items_param.packaging_method
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getPackagingMethod() {
        return packagingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.packaging_method
     *
     * @param packagingMethod the value for items_param.packaging_method
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setPackagingMethod(String packagingMethod) {
        this.packagingMethod = packagingMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.weight
     *
     * @return the value of items_param.weight
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.weight
     *
     * @param weight the value for items_param.weight
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setWeight(String weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.storage_method
     *
     * @return the value of items_param.storage_method
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getStorageMethod() {
        return storageMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.storage_method
     *
     * @param storageMethod the value for items_param.storage_method
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setStorageMethod(String storageMethod) {
        this.storageMethod = storageMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.eat_method
     *
     * @return the value of items_param.eat_method
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getEatMethod() {
        return eatMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.eat_method
     *
     * @param eatMethod the value for items_param.eat_method
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setEatMethod(String eatMethod) {
        this.eatMethod = eatMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.created_time
     *
     * @return the value of items_param.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.created_time
     *
     * @param createdTime the value for items_param.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_param.updated_time
     *
     * @return the value of items_param.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_param.updated_time
     *
     * @param updatedTime the value for items_param.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}