package com.imooc.pojo;

import java.util.Date;

public class ItemsImg {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_img.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_img.item_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_img.url
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_img.sort
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Integer sort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_img.is_main
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Integer isMain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_img.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_img.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_img.id
     *
     * @return the value of items_img.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_img.id
     *
     * @param id the value for items_img.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_img.item_id
     *
     * @return the value of items_img.item_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_img.item_id
     *
     * @param itemId the value for items_img.item_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_img.url
     *
     * @return the value of items_img.url
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_img.url
     *
     * @param url the value for items_img.url
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_img.sort
     *
     * @return the value of items_img.sort
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_img.sort
     *
     * @param sort the value for items_img.sort
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_img.is_main
     *
     * @return the value of items_img.is_main
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Integer getIsMain() {
        return isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_img.is_main
     *
     * @param isMain the value for items_img.is_main
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setIsMain(Integer isMain) {
        this.isMain = isMain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_img.created_time
     *
     * @return the value of items_img.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_img.created_time
     *
     * @param createdTime the value for items_img.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_img.updated_time
     *
     * @return the value of items_img.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_img.updated_time
     *
     * @param updatedTime the value for items_img.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}