package com.imooc.pojo;

import java.util.Date;

public class ItemsComments {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.user_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.item_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String itemId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.item_name
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String itemName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.item_spec_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String itemSpecId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.sepc_name
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String sepcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.comment_level
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Integer commentLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.content
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column items_comments.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.id
     *
     * @return the value of items_comments.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.id
     *
     * @param id the value for items_comments.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.user_id
     *
     * @return the value of items_comments.user_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.user_id
     *
     * @param userId the value for items_comments.user_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.item_id
     *
     * @return the value of items_comments.item_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.item_id
     *
     * @param itemId the value for items_comments.item_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setItemId(String itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.item_name
     *
     * @return the value of items_comments.item_name
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getItemName() {
        return itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.item_name
     *
     * @param itemName the value for items_comments.item_name
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.item_spec_id
     *
     * @return the value of items_comments.item_spec_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getItemSpecId() {
        return itemSpecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.item_spec_id
     *
     * @param itemSpecId the value for items_comments.item_spec_id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setItemSpecId(String itemSpecId) {
        this.itemSpecId = itemSpecId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.sepc_name
     *
     * @return the value of items_comments.sepc_name
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getSepcName() {
        return sepcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.sepc_name
     *
     * @param sepcName the value for items_comments.sepc_name
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setSepcName(String sepcName) {
        this.sepcName = sepcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.comment_level
     *
     * @return the value of items_comments.comment_level
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Integer getCommentLevel() {
        return commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.comment_level
     *
     * @param commentLevel the value for items_comments.comment_level
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setCommentLevel(Integer commentLevel) {
        this.commentLevel = commentLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.content
     *
     * @return the value of items_comments.content
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.content
     *
     * @param content the value for items_comments.content
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.created_time
     *
     * @return the value of items_comments.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.created_time
     *
     * @param createdTime the value for items_comments.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column items_comments.updated_time
     *
     * @return the value of items_comments.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column items_comments.updated_time
     *
     * @param updatedTime the value for items_comments.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}