package com.imooc.pojo;

import java.util.Date;

public class Users {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.username
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.password
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.nickname
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.realname
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.face
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String face;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.mobile
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.email
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.sex
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.birthday
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Date createdTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    private Date updatedTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.id
     *
     * @return the value of users.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.id
     *
     * @param id the value for users.id
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.username
     *
     * @return the value of users.username
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.username
     *
     * @param username the value for users.username
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.password
     *
     * @return the value of users.password
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.password
     *
     * @param password the value for users.password
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.nickname
     *
     * @return the value of users.nickname
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.nickname
     *
     * @param nickname the value for users.nickname
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.realname
     *
     * @return the value of users.realname
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.realname
     *
     * @param realname the value for users.realname
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.face
     *
     * @return the value of users.face
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getFace() {
        return face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.face
     *
     * @param face the value for users.face
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setFace(String face) {
        this.face = face;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.mobile
     *
     * @return the value of users.mobile
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.mobile
     *
     * @param mobile the value for users.mobile
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.email
     *
     * @return the value of users.email
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.email
     *
     * @param email the value for users.email
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.sex
     *
     * @return the value of users.sex
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.sex
     *
     * @param sex the value for users.sex
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.birthday
     *
     * @return the value of users.birthday
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.birthday
     *
     * @param birthday the value for users.birthday
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.created_time
     *
     * @return the value of users.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.created_time
     *
     * @param createdTime the value for users.created_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.updated_time
     *
     * @return the value of users.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public Date getUpdatedTime() {
        return updatedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.updated_time
     *
     * @param updatedTime the value for users.updated_time
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    public void setUpdatedTime(Date updatedTime) {
        this.updatedTime = updatedTime;
    }
}