package com.imooc.mapper;

import com.imooc.pojo.ItemsImg;
import java.util.List;

public interface ItemsImgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_img
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_img
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int insert(ItemsImg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_img
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    ItemsImg selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_img
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    List<ItemsImg> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_img
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int updateByPrimaryKey(ItemsImg record);
}