package com.imooc.mapper;

import com.imooc.pojo.ItemsComments;
import java.util.List;

public interface ItemsCommentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_comments
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_comments
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int insert(ItemsComments record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_comments
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    ItemsComments selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_comments
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    List<ItemsComments> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_comments
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int updateByPrimaryKey(ItemsComments record);
}