package com.imooc.mapper;

import com.imooc.pojo.ItemsParam;
import java.util.List;

public interface ItemsParamMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_param
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_param
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int insert(ItemsParam record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_param
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    ItemsParam selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_param
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    List<ItemsParam> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_param
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int updateByPrimaryKey(ItemsParam record);
}