package com.imooc.mapper;

import com.imooc.pojo.ItemsSpec;
import java.util.List;

public interface ItemsSpecMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int insert(ItemsSpec record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    ItemsSpec selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    List<ItemsSpec> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table items_spec
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int updateByPrimaryKey(ItemsSpec record);
}