package com.imooc.mapper;

import com.imooc.pojo.OrderItems;
import java.util.List;

public interface OrderItemsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int insert(OrderItems record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    OrderItems selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    List<OrderItems> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_items
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int updateByPrimaryKey(OrderItems record);
}