package com.imooc.mapper;

import com.imooc.pojo.UserAddress;
import java.util.List;

public interface UserAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int insert(UserAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    UserAddress selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    List<UserAddress> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_address
     *
     * @mbggenerated Fri Nov 06 14:01:52 CST 2020
     */
    int updateByPrimaryKey(UserAddress record);
}